services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port 9000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    packages:
      - libgl1-mesa-glx  # OpenCV dependency