services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port 9000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    packages:
      - build-essential
      - cmake
      - libopenblas-dev
      - liblapack-dev